/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:c0887be8-326b-43cb-a14a-e1142f6782f3",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_V9SDEEHx1",
  aws_user_pools_web_client_id: "g5v57176ba9kooofd8ahqqna1",
  oauth: {
    domain: "accountse1228520-e1228520-dev.auth.us-east-2.amazoncognito.com/",
    redirectSignIn: "http://localhost:3000",
    redirectSignOut: "http://localhost:3000",
    responseType: "code"
  },
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: []
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://flyy7othprdzdozrc5bpwqyqve.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-77wjprkponeqnopyhhbayn44ci"
};

export default awsmobile;
